name: crl-mm
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc=13.1.0
  - pip=22.3.1
  - python=3.7.16
  - setuptools=65.6.3
  - wheel=0.38.4
  - pip:
      - cloudpickle==1.6.0
      - cmake==3.26.4
      - filelock==3.12.2
      - gym==0.21.0
      - gym3==0.3.3
      - matplotlib==3.5.3
      - numpy==1.21.6
      #- nvidia-cublas-cu11==11.10.3.66
      #- nvidia-cuda-nvrtc-cu11==11.7.99
      #- nvidia-cuda-runtime-cu11==11.7.99
      #- nvidia-cudnn-cu11==8.5.0.96
      - pandas==1.3.5
      #- procgen==0.10.7
      - protobuf==3.20.3
      - scipy==1.7.3
      - stable-baselines3==1.8.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torch==1.13.1
prefix: /home/beksi/anaconda3/envs/sb3
